### PR TITLE
fix #122

### LINKED ISSUE #122: 404 on response from get_fedi_instances()
When I run get_fedi_instances(n = 5) using root 0.2.0, the response is:

Error in make_get_request(token = NULL, path = "/api/instances", instance = "api.index.community",  : 
  something went wrong. Status code: 404

From what I can see, api.index.community is responding with a 404 but is there a different server to get instances from? If so, is there a way of overriding instances variable in get_fedi_instances() ?

I am running something similar to:
library(rtoot)

instances <- get_fedi_instances(n = 5)
instances$name

### PR DESCRIPTION
**Pull request by schochastics**
@chainsawriot can you check this? I think I set everything up correctly, including hiding the token in the fixtures file

### CODE REVIEW

**Comment by schochastics** [comment]
obviously something fails. Do I need to do anything else with the token?

**Comment by chainsawriot** [comment]
On my machine, it's fixed.

**Comment by chainsawriot** [comment]
@schochastics I'll add one more test and rebase.

**Comment by chainsawriot** [comment]
Can be merged now.

**Pull request merged**
